default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  adapter: sqlite3
  database: db/development.sqlite3

test:
  <<: *default
  adapter: sqlite3
  database: db/test.sqlite3

production:
  primary:
    <<: *default
    adapter: postgresql
    url: <%= ENV.fetch("DATABASE_URL") { "postgres://localhost/cad_version_manager_production" } %>
  cable:
    <<: *default
    adapter: postgresql
    url: <%= ENV.fetch("DATABASE_URL") { "postgres://localhost/cad_version_manager_production" } %>
  cache:
    <<: *default
    adapter: postgresql
    url: <%= ENV.fetch("DATABASE_URL") { "postgres://localhost/cad_version_manager_production" } %>
  queue:
    <<: *default
    adapter: postgresql
    url: <%= ENV.fetch("DATABASE_URL") { "postgres://localhost/cad_version_manager_production" } %>
